### PR TITLE
Add monitoring of pool connection and queue state

### PR DESCRIPTION
**Pull request by jypma**
Unfortunately, the only current way to do that is to reflect deeply into
the internals of akka's pool implementation.

Let's hope that https://github.com/akka/akka-http/issues/1025 will yield
a more proper API for this.

### CODE REVIEW

**Comment by jypma** [comment]
Tests are missing, still looking into how to properly test this.

**Comment by jypma** [comment]
AND it doesn't work yet on scala 2.12 (compiler generates different class names)

**Comment by dpsoft** [comment]
@jypma I really like this PR, but also is a good idea also support scala 2.12 before merge. WDYT?

**Comment by jypma** [comment]
Sure. I'll look into it when I have time; ignore the current code, I accidentally pasted an early revision, where the postStop aspect actually is misspelled :-) I'll get back to it about a month from now (vacation...)

**Comment by ivantopo** [comment]
Hey folks, I'm closing this PR because it got outdated and we are moving all the code to the main Kamon repository.

**Pull request closed without merging**
