### PR TITLE
Add support for Scala 2.13.0

### PR DESCRIPTION
**Pull request by lustefaniak**
It still fails on FastFuture instrumentation test and requires released https://github.com/kamon-io/kamon-akka/pull/55

### CODE REVIEW

**Comment by lustefaniak** [comment]
I think the problem is with `intercept(method("transformWith$extension1")` as the instrumentation is not called at all if it is like that.

I see that the method to override should be 
```
// akka/http/scaladsl/util/FastFuture$.transformWith$extension:(Lscala/concurrent/Future;Lscala/Function1;Lscala/Function1;Lscala/concurrent/ExecutionContext;)Lscala/concurrent/Future;
```
But when I change
```
  onType("akka.http.scaladsl.util.FastFuture$")
    .intercept(method("transformWith$extension"), FastFutureTransformWithAdvice)
```
I get
```
Error => akka.http.scaladsl.util.FastFuture$ with message None of [protected void java.lang.Object.finalize() throws java.lang.Throwable, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException, public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll(), public scala.concurrent.Future kamon.instrumentation.akka.http.FastFutureTransformWithAdvice$.transformWith(scala.concurrent.Future,scala.Function1,scala.Function1,scala.concurrent.ExecutionContext,java.util.concurrent.Callable)] allows for delegation from public final scala.concurrent.Future akka.http.scaladsl.util.FastFuture$.transformWith$extension(scala.concurrent.Future,scala.Function1,scala.concurrent.ExecutionContext). Class loader: sun.misc.Launcher$AppClassLoader@18b4aac2: java.lang.IllegalArgumentException: None of [protected void java.lang.Object.finalize() throws java.lang.Throwable, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException, public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll(), public scala.concurrent.Future kamon.instrumentation.akka.http.FastFutureTransformWithAdvice$.transformWith(scala.concurrent.Future,scala.Function1,scala.Function1,scala.concurrent.ExecutionContext,java.util.concurrent.Callable)] allows for delegation from public final scala.concurrent.Future akka.http.scaladsl.util.FastFuture$.transformWith$extension(scala.concurrent.Future,scala.Function1,scala.concurrent.ExecutionContext)
```

Looks like encoding of extension methods changed as I can see `public final scala.concurrent.Future akka.http.scaladsl.util.FastFuture$.transformWith$extension(scala.concurrent.Future,scala.Function1,scala.concurrent.ExecutionContext)` which I quite different from the class definition in https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala-2.13%2B/akka/http/scaladsl/util/FastFuture.scala#L39

Any ideas what should be changed?

**Comment by lustefaniak** [comment]
Forwarder looks normal:
```
  public <B extends java.lang.Object> scala.concurrent.Future<B> transformWith(scala.Function1<A, scala.concurrent.Future<B>>, scala.Function1<java.lang.Throwable, scala.concurrent.Future<B>>, scala.concurrent.ExecutionContext);
    descriptor: (Lscala/Function1;Lscala/Function1;Lscala/concurrent/ExecutionContext;)Lscala/concurrent/Future;
    flags: ACC_PUBLIC
    Code:
      stack=5, locals=4, args_size=4
         0: getstatic     #41                 // Field akka/http/scaladsl/util/FastFuture$.MODULE$:Lakka/http/scaladsl/util/FastFuture$;
         3: aload_0
         4: invokevirtual #131                // Method future:()Lscala/concurrent/Future;
         7: aload_1
         8: aload_2
         9: aload_3
        10: invokevirtual #67                 // Method akka/http/scaladsl/util/FastFuture$.transformWith$extension:(Lscala/concurrent/Future;Lscala/Function1;Lscala/Function1;Lscala/concurrent/ExecutionContext;)Lscala/concurrent/Future;
        13: areturn
      LineNumberTable:
        line 39: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      14     0  this   Lakka/http/scaladsl/util/FastFuture;
            0      14     1     s   Lscala/Function1;
            0      14     2     f   Lscala/Function1;
            0      14     3 executor   Lscala/concurrent/ExecutionContext;
    Signature: #144                         // <B:Ljava/lang/Object;>(Lscala/Function1<TA;Lscala/concurrent/Future<TB;>;>;Lscala/Function1<Ljava/lang/Throwable;Lscala/concurrent/Future<TB;>;>;Lscala/concurrent/ExecutionContext;)Lscala/concurrent/Future<TB;>;
    MethodParameters:
      Name                           Flags
      s                              final
      f                              final
      executor                       final
```

**Comment by lustefaniak** [comment]
Hmmm, looks like my output was truncated, I see it exists:
```
public final <B, A> scala.concurrent.Future<B> transformWith$extension(scala.concurrent.Future<A>, scala.Function1<A, scala.concurrent.Future<B>>, scala.Function1<java.lang.Throwable, scala.concurrent.Future<B>>, scala.concurrent.ExecutionContext);
```

**Comment by lustefaniak** [comment]
@dpsoft Hey Diego, any idea what should I use in Kanela to overwrite that method?

**Comment by dpsoft** [comment]
@lustefaniak I think that your code is ok, but  I'll try take a look tonight.

**Comment by ivantopo** [comment]
Hey @lustefaniak, I just fixed the issue with `FastFuture` and merged to master already. I thought it was going to close this PR but nope :/, manually closing it now. Thanks a lot for starting the effort!

**Pull request closed without merging**
